# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/hima-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),hima)

include $(CLEAR_VARS)
LOCAL_MODULE := libTimeService
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES_64 := proprietary/vendor/lib64/libTimeService.so
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libTimeService.so
LOCAL_MULTILIB := both
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libmm-disp-apis
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES_64 := proprietary/vendor/lib64/libmm-disp-apis.so
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libmm-disp-apis.so
LOCAL_MULTILIB := both
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libtime_genoff
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES_64 := proprietary/vendor/lib64/libtime_genoff.so
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libtime_genoff.so
LOCAL_MULTILIB := both
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libshims_ims
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES_64 := proprietary/vendor/lib64/libshims_ims.so
LOCAL_MULTILIB := 64
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
#LOCAL_SRC_FILES := libshim_mediabuffer.cpp
#LOCAL_SHARED_LIBRARIES := libstagefright_foundation libui libgui
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_VENDOR_MODULE := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := TimeService
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/app/TimeService/TimeService.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := true
LOCAL_MODULE_SUFFIX := .apk
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ims
LOCAL_MODULE_OWNER := qti
#LOCAL_JAVA_LIBRARIES := telephony-common ims-common ims-ext-common ims-coext-common_system voip-common
#LOCAL_STATIC_JAVA_LIBRARIES := ims-ext-common ims-ext-common ims-ext-common_system
LOCAL_SRC_FILES := proprietary/app/ims/ims.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := true
LOCAL_MODULE_SUFFIX := .apk
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/app
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := imssettings
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/app/imssettings/imssettings.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := true
LOCAL_MODULE_SUFFIX := .apk
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/app
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := embms
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/app/embms/embms.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := true
LOCAL_MODULE_SUFFIX := .apk
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := VZWAPNLib
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/app/VZWAPNLib/VZWAPNLib.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_CLASS := APPS
LOCAL_DEX_PREOPT := true
LOCAL_MODULE_SUFFIX := .apk
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
include $(BUILD_PREBUILT)


include $(CLEAR_VARS)
LOCAL_MODULE := embmslibrary
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/framework/embmslibrary.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := imscmlibrary
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/framework/imscmlibrary.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := qcnvitems
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/framework/qcnvitems.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := qcrilhook
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/framework/qcrilhook.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := QtiTelephonyServicelibrary
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/framework/QtiTelephonyServicelibrary.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := qti-vzw-ims-internal
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/framework/qti-vzw-ims-internal.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rcsimssettings
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/framework/rcsimssettings.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := rcsservice
LOCAL_MODULE_OWNER := htc
LOCAL_SRC_FILES := proprietary/framework/rcsservice.jar
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := .jar
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := qcril
LOCAL_MODULE_OWNER := qcom
LOCAL_SRC_FILES := proprietary/qcril.db
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := DATA
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_SUFFIX := .db
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)
include $(BUILD_PREBUILT)

endif

#include $(CLEAR_VARS)
#LOCAL_MODULE := imssettings
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/app/imssettings/imssettings.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := true
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := VZWAPNLib
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/app/VZWAPNLib/VZWAPNLib.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := true
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := qti-vzw-ims-internal
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/framework/qti-vzw-ims-internal.jar
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := JAVA_LIBRARIES
#LOCAL_MODULE_SUFFIX := .jar
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := cneapiclient
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/framework/cneapiclient.jar
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := JAVA_LIBRARIES
#LOCAL_MODULE_SUFFIX := .jar
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := com.quicinc.cne.jar
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/framework/com.quicinc.cne.jar
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := JAVA_LIBRARIES
#LOCAL_MODULE_SUFFIX := .jar
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := imssettings
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/app/imssettings/imssettings.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := QAS_DVS_MSP
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/app/QAS_DVS_MSP/QAS_DVS_MSP.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := QtiTelephonyService
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/app/QtiTelephonyService/QtiTelephonyService.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := RCSBootstraputil
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/app/RCSBootstraputil/RCSBootstraputil.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := vzw_msdc_api
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/app/vzw_msdc_api/vzw_msdc_api.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := ims
#LOCAL_MODULE_OWNER := qti
#LOCAL_JAVA_LIBRARIES := telephony-common ims-common ims-ext-common_system voip-common
#LOCAL_STATIC_JAVA_LIBRARIES := ims-ext-common ims-ext-common_system
#LOCAL_SRC_FILES := proprietary/app/ims/ims.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := embms
#LOCAL_MODULE_OWNER := qcom
#LOCAL_SRC_FILES := proprietary/app/embms/embms.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_PRIVATE_PLATFORM_APIS := true
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := VZWAPNLib
#LOCAL_MODULE_OWNER := verizon
#LOCAL_SRC_FILES := proprietary/app/VZWAPNLib/VZWAPNLib.apk
#LOCAL_CERTIFICATE := platform
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := SHARED_LIBRARIES
#LOCAL_MODULE_CLASS := APPS
#LOCAL_PRIVATE_PLATFORM_APIS := true
#LOCAL_DEX_PREOPT := false
#LOCAL_MODULE_SUFFIX := .apk
#LOCAL_VENDOR_MODULE := true
#LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR)/app
#include $(BUILD_PREBUILT)

#LOCAL_PRIVATE_PLATFORM_APIS := true

#include $(CLEAR_VARS)
#LOCAL_MODULE := com.qti.dpmframework
#LOCAL_MODULE_OWNER := htc
#LOCAL_SRC_FILES := proprietary/framework/com.qti.dpmframework.jar
#LOCAL_MODULE_TAGS := optional
#LOCAL_MODULE_CLASS := JAVA_LIBRARIES
#LOCAL_MODULE_SUFFIX := .jar
#include $(BUILD_PREBUILT)

#include $(CLEAR_VARS)
#LOCAL_MODULE := com.qti.dpmframework
#LOCAL_MODULE_OWNER := htc#LOCAL_SRC_FILES := proprietary/framework/com.qti.dpmframework.ja
#LOCAL_MODULE_TAGS := optionl
#LOCAL_MODULE_CLASS := JAVALIBRARIES
#LOCAL_MODULE_SUFFIX := .jar
#include $(BUILD_PREBUILT)
